project:
  name: col 
  images:
    academy: thp.sangre.fi:4999/colosseum/academy:v1-4-0
    website: thp.sangre.fi:4999/colosseum/website:v1-1-1
  drupal:
    academy:
      base_url: 'https://academy.colosseumdental.com'
    website:
      base_url: 'https://www.colosseumdental.com'

